Clarify workflow variables and functions
- Rename workflow variables and scripts to be more self-explanatory
- Commit processing script which should already have been in the repo

However, this doesn't currently work:
TypeError: gather_odb_results() missing 1 required positional argument: 'combined_odb_results'